FROM golang:1.22.3 AS build

RUN mkdir /app
COPY . /app
WORKDIR /app
RUN CGO_ENABLED=0 go build -trimpath -ldflags "-s -w -extldflags '-static'" -installsuffix cgo -tags netgo -o api-bsc -v block/app.go
RUN strip /app/api-bsc

FROM scratch AS base
LABEL name="api-bsc" \
    version="0.1.17"
WORKDIR /

COPY --from=build /app/api-bsc ./

CMD ["/api-bsc"]