FROM golang:1.22.3 AS build

RUN mkdir /app
COPY . /app
WORKDIR /app
RUN CGO_ENABLED=0 go build -trimpath -ldflags "-s -w -extldflags '-static'" -installsuffix cgo -tags netgo -o api-cbs -v block/app.go
RUN strip /app/api-cbs

FROM scratch AS base
LABEL name="api-cbs" \
    version="0.1.0"
WORKDIR /

COPY --from=build /app/api-cbs ./

CMD ["/api-cbs"]